- .github/workflows/merge.yml
- .github/workflows/pr-open.yml
Add an approval process in the test and prod environments.
> feat: Added environment branch protection rules

- .github/workflows/merge.yml
The goal of this PR is to ensure that there’s always an ever-present deployment of Case Management in the dev environment that matches what’s in test.  Deployments to dev/test (and eventually prod) are handled via helm and argo.  When a PR is approved and moved to test, an image is uploaded to GHCR (github container repo) with a specific tag (a sequential number).  The github action for test deployments has been updated to set the tag in values-static.yaml.  Argo detects changes to this file and deploys it if there are any changes.  Since this file is updated with the same tag used for test deployments, argo should deploy the same test image to the dev environment (argo itself knows that values-static.yaml is associated with the dev environment, that information isn’t within the ghcr …
> feat: CE-625 Round 2

- migrations/sql/V1.18.0__CE-693.sql
---
- [Backend](https://nr-compliance-enforcement-cm-63-backend.apps.silver.devops.gov.bc.ca/api)
> feat: CE-693 change varchar4000 to text

- backend/src/action_code/action_code.service.ts
- backend/src/case_file_action/case_file_action.service.ts
- migrations/sql/V1.21.0__CE-829.sql
---
- [Backend](https://nr-compliance-enforcement-cm-68-backend.apps.silver.devops.gov.bc.ca/api)
> fix: CE-829 prevention actions list order

- .github/workflows/merge.yml
- backend/src/app.ts
Updated deploy key to connect to the gitops repo for production migrations.
Failure to connect to gitops repo.
---
- [Backend](https://nr-compliance-enforcement-cm-71-backend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/ …
> fix: Added deploy key for production releases

- backend/src/case_file/case_file.service.ts
---
- [Backend](https://nr-compliance-enforcement-cm-72-backend.apps.silver.devops.gov.bc.ca/api)
> fix: officer,date outcome animal bug

- backend/package-lock.json
---
- [Backend](https://nr-compliance-enforcement-cm-73-backend.apps.silver.devops.gov.bc.ca/api)
> chore: update packages with high vulnerability

- backend/package-lock.json
---
- [Backend](https://nr-compliance-enforcement-cm-74-backend.apps.silver.devops.gov.bc.ca/api)
> chore: CE-861 update nodejs-ws package

- backend/src/age_code/age_code.resolver.ts
- backend/src/conflict_history_code/conflict_history_code.resolver.ts
- backend/src/drug_code/drug_code.resolver.ts
- backend/src/drug_method_code/drug_method_code.resolver.ts
- backend/src/drug_remaining_outcome_code/drug_remaining_outcome_code.resolver.ts
- backend/src/ear_code/ear_code.resolver.ts
- backend/src/enum/role.enum.ts
- backend/src/equipment_code/equipment_code.resolver.ts
- backend/src/hwcr_assessment_action/hwcr_assessment_action.resolver.ts
- backend/src/hwcr_outcome_code/hwcr_outcome_code.resolver.ts
- backend/src/hwcr_prevention_action/hwcr_prevention_action.resolver.ts
- backend/src/inaction_justification_type/inaction_justification_type.resolver.ts
- backend/src/sex_code/sex_code.resolver.ts
- backend/src/threat_level_code/threat_level_code.resolver.ts
This PR is to allow CEEB officers to use NatComplaints. For correct functioning NatComplaints needs to load code tables that include those from Case Management.  This change is to set the necessary permissions for that. In future we may modify the application to only load code tables that correspond to the user role but it is outside the scope of this ticket.  
Fixes # (CE-927)
---
- [Backend](https://nr-compliance-enforcement-cm-77-backend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in draft mode. …
> feat: CE-927-Allow-CEEB-users-to-only-create-complaint-types-of-waste-and-pesticides

- .github/workflows/scheduled.yml
- backend/src/age_code/age_code.resolver.ts
- backend/src/conflict_history_code/conflict_history_code.resolver.ts
- backend/src/drug_code/drug_code.resolver.ts
- backend/src/drug_method_code/drug_method_code.resolver.ts
- backend/src/drug_remaining_outcome_code/drug_remaining_outcome_code.resolver.ts
- backend/src/ear_code/ear_code.resolver.ts
- backend/src/enum/role.enum.ts
- backend/src/equipment_code/equipment_code.resolver.ts
- backend/src/hwcr_assessment_action/hwcr_assessment_action.resolver.ts
- backend/src/hwcr_outcome_code/hwcr_outcome_code.resolver.ts
- backend/src/hwcr_prevention_action/hwcr_prevention_action.resolver.ts
- backend/src/inaction_justification_type/inaction_justification_type.resolver.ts
- backend/src/sex_code/sex_code.resolver.ts
- backend/src/threat_level_code/threat_level_code.resolver.ts
---
- [Backend](https://nr-compliance-enforcement-cm-78-backend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/a …
> feat: Release/giant pacific octopus

- backend/src/case_file/case_file.resolver.ts
---
- [Backend](https://nr-compliance-enforcement-cm-82-backend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/a …
> feat: CE-1003 Add notes to CEEB complaint outcome

- migrations/sql/V1.29.0__CE-590.sql
---
- [Backend](https://nr-compliance-enforcement-cm-96-backend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/a …
> chore: CE-590 standardized actor guid

- backend/src/case_file/case_file_inputs.graphql
- backend/src/case_file/dto/assessment-details.input.ts
Adding the functionality of linking two complaints was added to NATCom. While the links are recorded in that database, the process occurs when creating a new assessment. The `actionLinkedComplaintIdentifier` is included in the payload to Case Management, but is not used here yet.
Fixes # CE-634
---
- [Backend](https://nr-compliance-enforcement-cm-97-backend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …
> feat: Add actionLinkedComplaintIdentifier to AssessmentDetailsInput

- backend/src/configuration/configuration.resolver.ts
This PR is to fix a bug of Case Management code table version not populating
Fixes # (CE-1201)
---
- [Backend](https://nr-compliance-enforcement-cm-102-backend.apps.silver.devops.gov.bc.ca/api)
> fix: CE-1201-Case-Management-Code-Table-Version-not-Populating

- migrations/sql/R__code-table-data.sql.sql
---
- [Backend](https://nr-compliance-enforcement-cm-103-backend.apps.silver.devops.gov.bc.ca/api) …
> fix: make insert repeatable

- backend/src/case_file/case_file.service.ts
- backend/src/case_file/case_file_types.graphql
- backend/src/case_file/dto/subject-query-result.ts
- backend/src/case_file/entities/wildlife-entity.ts
Fixes # (issue) CE-248
---
- [Backend](https://nr-compliance-enforcement-cm-106-backend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> feat: return descriptions for HWCR export

- exports/cos_hwcr_case_export.sql
Moves monthly export queries to version control
> chore: add export

- migrations/sql/R__code-table-data.sql.sql
Added "Unfounded" to animal actions, and modified "Injured, present" to be "Injured/Distressed/Deceased"
https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1288
Code table value update
---
- [Backend](https://nr-compliance-enforcement-cm-109-backend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore: Update animal action values

- migrations/sql/R__code-table-data.sql.sql
Updated the wording of an animal action to include "Present" by user request.
Fixes # https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1299
This was tested by rerunning the database migrations and verifying in NatCom that the new value is what is presented in the animal actions list.
---
- [Backend](https://nr-compliance-enforcement-cm-111-backend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore: Update animal action workding

- docker-compose.yml
- migrations/sql/R__code-table-data.sql.sql
Simply updates the `Neck snare` equipment code to `Snare`
- Also includes a docker compose tweak to ensure migrations succeed in order for the backend to come up, enforcing migration errors are resolved
---
- [Backend](https://nr-compliance-enforcement-cm-118-backend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
> chore: update necksnare to snare

- migrations/sql/R__code-table-data.sql.sql
Add GIR case code.
GIR complaints for the COS now have the additional notes section which counts as an outcome, and thus needs to exist in case management. This PR handles adding the GIR case code so that the cases can be created.
Fixes # 1138
https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1138
Sibling branch in NatCom: https://github.com/bcgov/nr-compliance-enforcement/pull/897
---
- [Backend](https://nr-compliance-enforcement-cm-119-backend.apps.silver.devops.gov.bc.ca/ …
> feat: Add GIR to case_code table

- backend/prisma/schema.prisma
- backend/src/case_file/case_file.service.ts
- backend/src/case_file/case_file_inputs.graphql
- backend/src/case_file/case_file_types.graphql
- backend/src/case_file/dto/equipment/create-equipment-details.input.ts
- backend/src/case_file/dto/equipment/update-equipment-details.input.ts
- backend/src/case_file/entities/equipment.entity.ts
- backend/src/equipment_code/equipment_code.graphql
- backend/src/equipment_code/equipment_code.service.ts
- migrations/sql/R__code-table-data.sql.sql
- migrations/sql/V1.36.0__CE-1326.sql
https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1326
---
- [Backend](https://nr-compliance-enforcement-cm-120-backend.apps.silver.devops.gov.bc.ca/api)
> feat: CE-1326 Add Quantity for Equipment

- backend/src/age_code/age_code.resolver.ts
- backend/src/auth/decorators/roles.decorator.ts
- backend/src/case_file/case_file.resolver.ts
- backend/src/ceeb_decision_action/ceeb_decision_action.resolver.ts
- backend/src/code-tables/case_location_code/case_location_code.resolver.ts
- backend/src/code-tables/discharge_code/discharge_code.resolver.ts
- backend/src/code-tables/non_compliance_code/non_compliance.resolver.ts
- backend/src/code-tables/schedule_code/schedule_code.resolver.ts
- backend/src/code-tables/sector_code/sector_code.resolver.ts
- backend/src/configuration/configuration.resolver.ts
- backend/src/conflict_history_code/conflict_history_code.resolver.ts
- backend/src/drug_code/drug_code.resolver.ts
- backend/src/drug_method_code/drug_method_code.resolver.ts
- backend/src/drug_remaining_outcome_code/drug_remaining_outcome_code.resolver.ts
- backend/src/ear_code/ear_code.resolver.ts
- backend/src/enum/role.enum.ts
- backend/src/equipment_code/equipment_code.resolver.ts
- backend/src/hwcr_assessment_action/hwcr_assessment_action.resolver.ts
- backend/src/hwcr_outcome_code/hwcr_outcome_code.resolver.ts
- backend/src/hwcr_prevention_action/hwcr_prevention_action.resolver.ts
- backend/src/inaction_justification_type/inaction_justification_type.resolver.ts
- backend/src/lead/lead.resolver.ts
- backend/src/schedule_sector_xref/schedule_sector_xref.resolver.ts
- backend/src/sex_code/sex_code.resolver.ts
- backend/src/threat_level_code/threat_level_code.resolver.ts
Fixes # CE-1379
---
- [Backend](https://nr-compliance-enforcement-cm-121-backend.apps.silver.devops.gov.bc.ca/api) …
> feat: Add Parks role

- migrations/sql/V1.37.1__CE-1148.sql
Corrects an issue with data migration of note data
> fix: CE-1148

- exports/cos_hwcr_case_export.sql
- Provide the original species and outcome
- Include Attended flag
- Filter out GIRs by only exporting HWCR and ERS
Fixes # CE-1443
> feat: Export Updates

- backend/prisma/schema.prisma
- backend/src/app.module.ts
- backend/src/case_file/case_file.service.ts
- backend/src/case_file/case_file_inputs.graphql
- backend/src/case_file/case_file_types.graphql
- backend/src/case_file/dto/ceeb/decision/decision-input.ts
- backend/src/case_file/entities/decision-entity.ts
- backend/src/ipm_auth_category_code/entities/ipm_auth_category_code.entity.ts
- backend/src/ipm_auth_category_code/ipm_auth_category_code.graphql
- backend/src/ipm_auth_category_code/ipm_auth_category_code.module.ts
- backend/src/ipm_auth_category_code/ipm_auth_category_code.resolver.spec.ts
- backend/src/ipm_auth_category_code/ipm_auth_category_code.resolver.ts
- backend/src/ipm_auth_category_code/ipm_auth_category_code.service.spec.ts
- backend/src/ipm_auth_category_code/ipm_auth_category_code.service.ts
- exports/ceeb_quarterly_case_export.sql
- migrations/sql/R__code-table-data.sql.sql
- migrations/sql/V1.38.0__CE-1084.sql
Adds a new code table for the IPM Authorization Category and ties it into the decision.
Fixes # CE-1084
---
- [Backend](https://nr-compliance-enforcement-cm-127-backend.apps.silver.devops.gov.bc.ca/api)
After merge, new images …
> feat: Add IPM Authorization Category to CEEB Decision

- .github/workflows/merge-to-release.yaml
---
- [Backend](https://nr-compliance-enforcement-cm-129-backend.apps.silver.devops.gov.bc.ca/api) …
> fix: static tag getter in pipeline

- migrations/sql/R__code-table-data.sql.sql
This PR is to add choices for drop downs and selections (COS Outcomes) based on various user feedback
Fixes # (CE-1448)
> feat: CE-1448-Additional-choices-for-drop-downs-and-selections-(COS-Outcomes)

- migrations/sql/R__code-table-data.sql.sql
> feat: CE-1448-Update-animal-outcome

- migrations/sql/R__code-table-data.sql.sql
> feat: Release Sassy Bighorn Sheep

- .github/workflows/pr-open.yml
---
- [Backend](https://nr-compliance-enforcement-cm-143-backend.apps.silver.devops.gov.bc.ca/api) …
> fix: keep all image builds

- .github/workflows/pr-open.yml
> fix: keep all image builds (#143)

- backend/dataloader/bulk-data-loader.js
---
- [Backend](https://nr-compliance-enforcement-cm-145-backend.apps.silver.devops.gov.bc.ca/api)
> chore: bump build

- backend/src/case_management/case_file/case_file.service.ts
---
- [Backend](https://nr-compliance-enforcement-cm-149-backend.apps.silver.devops.gov.bc.ca/api) …
> chore: 1.6 version bump v2

- backend/src/case_management/agency_code/agency_code.resolver.ts
---
- [Backend](https://nr-compliance-enforcement-cm-157-backend.apps.silver.devops.gov.bc.ca/api) …
> fix: Missing Parks role on Agency table

- exports/ceeb_quarterly_case_export.sql
- migrations/sql/R__grants.sql
---
- [Backend](https://nr-compliance-enforcement-cm-153-backend.apps.silver.devops.gov.bc.ca/api) …
> feat: Updates to CEEB export found during latest quarterly run

- .github/workflows/pr-close.yml
- .github/workflows/pr-open.yml
- backend/package-lock.json
- backend/package.json
- backend/prisma/shared/generated/index.ts
- backend/prisma/shared/generated/park.ts
- backend/prisma/shared/shared.prisma
- backend/src/app.module.ts
- backend/src/case_management/agency_code/agency_code.resolver.ts
- backend/src/middleware/mapper.ts
- backend/src/shared/park/dto/park.input.ts
- backend/src/shared/park/dto/park.ts
- backend/src/shared/park/park.module.ts
- backend/src/shared/park/park.resolver.ts
- backend/src/shared/park/park.service.ts
- backend/src/shared/park/park_functions.graphql
- backend/src/shared/park/park_inputs.graphql
- backend/src/shared/park/park_types.graphql
- exports/ceeb_quarterly_case_export.sql
- migrations/sql/R__code-table-data.sql.sql
- migrations/sql/R__grants.sql
- migrations/sql/shared/V1.40_1__CE-1535.sql
- migrations/test-only-migrations/shared/R__park-test-data.sql
> feat: Release - Sus Sasquatch

- backend/src/shared/park/park.service.ts
---
- [Backend](https://nr-compliance-enforcement-cm-167-backend.apps.silver.devops.gov.bc.ca/api) …
> feat: Add park areas to Park query

- backend/src/case_management/case_file/case_file.service.ts
---
- [Backend](https://nr-compliance-enforcement-cm-171-backend.apps.silver.devops.gov.bc.ca/api) …
> chore: unclog pipeline

- backend/src/case_management/case_file/case_file.service.ts
---
- [Backend](https://nr-compliance-enforcement-cm-172-backend.apps.silver.devops.gov.bc.ca/api) …
> chore: attempt 2 at unclogging the pipeline

- backend/src/shared/park/parkArea.resolver.ts
- backend/src/shared/park/parkArea.service.ts
- backend/src/shared/park/park_functions.graphql
---
- [Backend](https://nr-compliance-enforcement-cm-176-backend.apps.silver.devops.gov.bc.ca/api) …
> feat: CE-1542 Add park area to Admin page

- backend/src/shared/park/park.resolver.ts
- backend/src/shared/park/park.service.ts
- backend/src/shared/park/park_functions.graphql
This PR contains GraphQL query to support filtering by park area in NatCom
Fixes # (CE-1576)
---
- [Backend](https://nr-compliance-enforcement-cm-177-backend.apps.silver.devops.gov.bc.ca/api)
> feat: CE-1576-BC-Parks-filter-by area

- migrations/sql/V1.43.2__CE-1455.sql
---
- [Backend](https://nr-compliance-enforcement-cm-178-backend.apps.silver.devops.gov.bc.ca/api)
> fix: CE-1455 Data fix

- backend/src/case_management/case_file_action/case_file_action.service.ts
---
- [Backend](https://nr-compliance-enforcement-cm-181-backend.apps.silver.devops.gov.bc.ca/api)
> chore: Extra error logging

- backend/package-lock.json
- backend/prisma/case_management/case_management.prisma
- backend/src/case_management/case_file/case_file.resolver.ts
- backend/src/case_management/case_file/case_file.service.ts
- backend/src/case_management/case_file/case_file_functions.graphql
- backend/src/case_management/case_file/case_file_inputs.graphql
- backend/src/case_management/case_file/case_file_types.graphql
- backend/src/case_management/case_file/dto/create-case_file.input.ts
- backend/src/case_management/case_file/dto/delete-prevention.input.ts
- backend/src/case_management/case_file/dto/prevention.input.ts
- backend/src/case_management/case_file/dto/update-case_file.input.ts
- backend/src/case_management/case_file/entities/case_file.entity.ts
- backend/src/case_management/case_file/entities/prevention.entity.ts
- migrations/sql/V1.43.3__CE-1592.sql
Addresses https://env-ceds.atlassian.net/browse/CE-1592
---
- [Backend](https://nr-compliance-enforcement-cm-180-backend.apps.silver.devops.gov.bc.ca/api)
> feat: CE-1592 Multiple Prevention and Education

- backend/prisma/case_management/case_management.prisma
- backend/src/case_management/case_file/case_file.service.ts
- backend/src/case_management/case_file/case_file_types.graphql
- backend/src/case_management/case_file/dto/note/delete-note.input.ts
- backend/src/case_management/case_file/dto/note/update-note.input.ts
- backend/src/case_management/case_file/entities/note.entity.ts
- migrations/sql/V1.44.2__CE-1624.sql
This PR is to allow editing notes, assessment and prevention/education only by the agency which added them.
Fixes # (CE-1624)
---
- [Backend](https://nr-compliance-enforcement-cm-190-backend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/ …
> feat: CE-1624 Lead agency of a complaint cannot edit data provided by other agency

- backend/src/case_management/case_file/case_file.service.ts
---
- [Backend](https://nr-compliance-enforcement-cm-188-backend.apps.silver.devops.gov.bc.ca/api) …
> feat: Support for updating agency on assessment

- exports/cos_hwcr_case_export.sql
---
- [Backend](https://nr-compliance-enforcement-cm-192-backend.apps.silver.devops.gov.bc.ca/api) …
> feat: remove case notes, multiple wildlife bug

- migrations/sql/R__code-table-data.sql.sql
This PR is to update and re-order Prevention and Education and Outcomes options
Fixes # (CE-1708)
> feature: CE-1708 Changes to Prevention and Education and Outcomes based on user feedback

- backend/src/case_management/case_file/case_file.service.ts
This PR is to ensure P&E actions are saved in the same order as they appear as selectable options
Fixes # (CE-1777)
---
- [Backend](https://nr-compliance-enforcement-cm-205-backend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/workflows/ …
> fix: CE-1777 P&E Options saving in inconsistent order

- backend/src/case_management/case_file/case_file.service.ts
- backend/src/case_management/code-tables/discharge_code/discharge_code.service.ts
- exports/cos_assessment_export.sql
- exports/cos_hwcr_case_export.sql
- exports/cos_hwcr_equipment_export.sql
- migrations/sql/R__code-table-data.sql.sql
> feat: release 2.2 Scholarly Stegosaraus

- backend/src/case_management/case_file/case_file.service.ts
- migrations/test-only-migrations/shared/R__person-test-data.sql
---
- [Backend](https://nr-compliance-enforcement-cm-212-backend.apps.silver.devops.gov.bc.ca/api) …
> chore: Bump2

- README.md
---
- [Backend](https://nr-compliance-enforcement-cm-214-backend.apps.silver.devops.gov.bc.ca/api) …
> chore: flush pipeline

- backend/src/case_management/case_file/case_file.service.ts
---
- [Backend](https://nr-compliance-enforcement-cm-215-backend.apps.silver.devops.gov.bc.ca/api)
> chore: bump3

- backend/src/case_management/case_file/case_file.service.ts
---
- [Backend](https://nr-compliance-enforcement-cm-216-backend.apps.silver.devops.gov.bc.ca/api) …
> chore: flush cicd

- backend/dataloader/bulk-data-loader.js
- migrations/sql/R__code-table-data.sql.sql
Fixes # CE-1799
Removes options from the Complaint List filters that have been deprecated.   There is no data in either test or production that references these options.
---
- [Backend](https://nr-compliance-enforcement-cm-226-backend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …
> feat: Remove unused filter options

- migrations/sql/R__code-table-data.sql.sql
---
- [Backend](https://nr-compliance-enforcement-cm-229-backend.apps.silver.devops.gov.bc.ca/api) …
> fix: Order outcome filter alphabetically

- backend/src/case_management/lead/lead.service.ts
Fixes # CE-1857
---
- [Backend](https://nr-compliance-enforcement-cm-238-backend.apps.silver.devops.gov.bc.ca/api) …
> fix: Update outcome filter to only return active outcomes

- backend/src/shared/case_file/case_file.resolver.ts
- backend/src/shared/case_file/case_file.service.ts
- backend/src/shared/case_file/case_file_functions.graphql
Added a function to get a case GUID using an activity type and ID.
Fixes # [(issue)](https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1859)
---
- [Backend](https://nr-compliance-enforcement-cm-239-backend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …
> feat: CE-1959 Add getCaseFileByActivityId

- backend/prisma/shared/generated/business.ts
- backend/prisma/shared/generated/business_h.ts
- backend/prisma/shared/generated/index.ts
- backend/prisma/shared/generated/party.ts
- backend/prisma/shared/generated/party_h.ts
- backend/prisma/shared/generated/party_type_code.ts
- backend/prisma/shared/shared.prisma
- backend/src/app.module.ts
- backend/src/middleware/mapper.ts
- backend/src/shared/business/business_types.graphql
- backend/src/shared/business/dto/business.ts
- backend/src/shared/party/dto/party.ts
- backend/src/shared/party/party.module.ts
- backend/src/shared/party/party.resolver.ts
- backend/src/shared/party/party.service.ts
- backend/src/shared/party/party_functions.graphql
- backend/src/shared/party/party_types.graphql
- migrations/sql/shared/R__party.sql
- migrations/sql/shared/V1.50.1__CE-1802_view_parties.sql
- migrations/sql/shared/V1.50.3__CE-1802_view_parties.sql
- migrations/test-only-migrations/shared/R__party-test-data.sql
This PR is to allow users access and display a details page for parties of interest within NatCom.
Fixes # (CE-1802)
---
- [Backend](https://nr-compliance-enforcement-cm-245-backend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement-cm/actions/workflows …
> feat: CE-1802 View Party Details

- backend/src/investigation/investigation/dto/investigation.ts
- backend/src/investigation/investigation/investigation.graphql
- backend/src/investigation/investigation/investigation.module.ts
- backend/src/investigation/investigation/investigation.resolver.ts
- backend/src/investigation/investigation/investigation.service.ts
---
- [Backend](https://nr-compliance-enforcement-cm-252-backend.apps.silver.devops.gov.bc.ca/api) …
> feat: CE-1811 view list of investigations

- backend/package-lock.json
- backend/prisma/shared/generated/case_file_h.ts
- backend/prisma/shared/shared.prisma
- backend/src/app.module.ts
- backend/src/investigation/investigation/dto/investigation.ts
- backend/src/investigation/investigation/investigation.graphql
- backend/src/investigation/investigation/investigation.module.ts
- backend/src/investigation/investigation/investigation.resolver.ts
- backend/src/investigation/investigation/investigation.service.ts
- backend/src/investigation/investigation/investigation_functions.graphql
- backend/src/investigation/investigation/investigation_types.graphql
- backend/src/middleware/mapper.ts
- backend/src/shared/business/business_inputs.graphql
- backend/src/shared/party/dto/party.ts
- backend/src/shared/party/party.resolver.ts
- backend/src/shared/party/party.service.ts
- backend/src/shared/party/party_functions.graphql
- backend/src/shared/party/party_types.graphql
- backend/src/shared/party_type_code/dto/party_type_code.ts
- backend/src/shared/party_type_code/party_type_code.module.ts
- backend/src/shared/party_type_code/party_type_code.resolver.ts
- backend/src/shared/party_type_code/party_type_code.service.ts
- backend/src/shared/party_type_code/party_type_code_functions.graphql
- backend/src/shared/party_type_code/party_type_code_types.graphql
> feat: 2.6 Hypnotic Hippogriff
